name: Feature Request
description: Suggest a new feature or improvement for Weather Gains
title: "[FEATURE] "
labels: ["enhancement"]
assignees: ["RobuxTRex"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature for **Weather Gains**!
        Please describe your idea clearly so it can be discussed.

  - type: textarea
    id: description
    attributes:
      label: Problem
      description: What problem are you trying to solve with this feature?
      placeholder: It's difficult to change multipliers!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see added.
      placeholder: Add a config option to change multipliers in-game.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional Context
      description: Add references or other info if relevant.
      placeholder: ... 

  - type: markdown
    attributes:
      value: "---"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to follow the [Code of Conduct](https://github.com/RobuxTRex/Weather-Gains-LC/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the Code of Conduct
          required: true